version: '2'
services:
    saidmamonoweb-app:
        image: saidmamonoweb
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://saidmamonoweb-mysql:3306/saidmamonoweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://saidmamonoweb-elasticsearch:9200
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    saidmamonoweb-mysql:
        extends:
            file: mysql.yml
            service: saidmamonoweb-mysql
    saidmamonoweb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: saidmamonoweb-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
